services:
  postgres:
    image: postgres:16
    container_name: mail-sentinel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "mail-sentinel"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Your DB PASSWORD"
    ports:
      - "5432:5432"
    volumes:
      - mail_sentinel_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mail-sentinel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - mail_sentinel_redis:/data

volumes:
  mail_sentinel_postgres:
  mail_sentinel_redis:
